language: php

php:
    - 5.6
    - 5.5
    - 5.4
before_script:
    - composer install
    - ./bin/serve > /dev/null 2>&1 &
    - ./bin/migrate

script:
    - vendor/bin/phpspec run -v
    - phpunit 
